### ISSUE TITLE
LocalDate methods

### ISSUE THREAD

**Issue by denysLystopadskyy** [DmytroPazykov/spring-boot#3]
https://github.com/DmytroPazykov/user-provider-service/blob/6ee0084a73b73a7cdfbbc742ee06640e2b116979/src/main/java/com/astt/strt/component/ScheduledTasks.java#L29

Maybe it's better to count death_time and move it to local variable?
Also  localDate.isBefore() method can help.

**Comment by DmytroPazykov** [comment]
The implementation now has a bit another structure
